# A Magnetorheological Fluid Yield Stress Measurement Platform by Movable Permanent Magnet

Ping-Hsun Lee, Jen-Yuan (James) Chang

_Department of Power Mechanical Engineering, National Tsing Hua University, Hsinchu, Taiwan_

###### Abstract

In this paper we propose a platform for measuring shear force of magnetorheological fluid (MRF) by which the relationship of yield stress and magnetic flux of specific material can be determined. With the proposed platform, the drawing shear force and the corresponding yield stress contributed by MRF can be evaluated in respect to the strength and direction of given magnetic field with acceptable accuracy for specific designing purposes without large, complex, and expensive instrument.

_Index Terms - MR fluid, yield stress, permanent magnet._

## I Introduction

A magneto-rheological fluid (MRF) is a smart material that consists of micro-sized magnetic particles dispersed in a carrier fluid such as oil. Without external magnetic field it appears as normal viscous fluid. With external magnetic field the magnetized particles link as chains that restrict the movement of the fluid, hence make the MRF resistive to shear force. This reaction is reversible and responses in several tens of millisecond [1-2]. Many devices such as damper, brake, etc. employed the MRF effect such that their properties can be controlled by changing magnetic fields [3-5].

## II Approach

Although the datasheets of specific MRF were provided by their vendors, it is still necessary to well know about the mechanical properties between the MRF and specific materials and its surface treatment adopting for specific device designing, especially for MRF of customized ingredient. Furthermore, the quantity of the properties such as yielding stress depends on the analytical technique used. Many studies for yielding stress of MRF were carried out by utilizing a rotational rheometer consisted of a pair of disks with MRF filled between and magnetic field generated by electro-magnet passing through [6-7]. Although commercial rheometers for these purposes were available, it may not be practical to be equipped by general laboratories due to their costs and footprints.

In this paper we proposed a device which was designed specifically for measuring the shear force between MRF and specific materials. Although magnetic fields are easier to be controlled by electromagnet, the requirement of high current and corresponding power consumption as well as the generated heat would affect the property of MRF hence additional cooling and control system are required to keep the temperature constant. Therefore, the magnetic field of the device proposed in this study would be produced by two blocks of permanent magnets to save the power supply and cooling system for keeping a constant temperature at the MRF working zone.

The magnitude of magnetic field can be adjusted by changing the distance between the magnets and the specimens. Furthermore, the ideal situation where the direction of the magnetic field is perpendicular to the shear layer of MRF is not always true for devices with a complex structure, the proposed design allowing the direction of specimens inside the circular tube to be adjusted relative to the magnetic field by rotating the circular tube in the center hole of the frame body.

The magnetic flux in the device was measured by Gauss meter, and the shear force between the specimens and MRF was measured by push-pull force gauge so the shear stress could be obtained accordingly by divided the corresponding area and hence the relationship of yielding shear stress and the magnetic flux. The proposed device is consisted of three components, namely a center tube in the frame body and two outside permanent magnets placed oppositely as shown in Figure 1. The simplicity and practical of the proposed device would be verified after series of measurements being carried out.

Fig.1 The schematic and nomenclature of the proposed measurement platform.

## Acknowledgment

The authors appreciate the support from Ministry of Science and Technology of Taiwan under the grant MOST 106-2218-E-007-023 for the work described herein.

## References

* [1] M. K. Kale, R. Tuzeny, "Properties and Applications of magnetic-chaological fluids," _J. of Achemoelectrika in Materials and Mard. Fey._, vol.18, pp. 127-130 (2006).
* [2] A. G. Dubin and A. G. G. Dubin, "Design and application of magnetic-chaological fluid," _Magnetic and Mobile_, vol. 38, pp. 2656-2667 (2007).
* [3] M. K. Kale, "A tutorial of magnetic and magnetic-chaological fluids," _Magnetic and Magnetic Materials and Structures_, vol. 10, pp. 15-35 (1999).
* [4] J. Wang, M. "Magnetohydrodynamic Fluid Mechanics: Principles, Chapters and Applications in Mechanical Engineering," _Proc. Mach Mach Resp._, vol. 21, pp. 165-174 (2001).
* [5] A. Spagnia, "Properties and Applications of Magnetohydrodynamical fluids," _Frontiers of Industrial Science_, vol. 21, pp. 74-74 (2011).
* [6] E. Lemaire, G. Bonitz, "Yetl'Skyat and Wall effects in Magnetic Colloid Suppression," _J. Phys. D: Appl. Phys._, vol. 12, pp. 412-447 (1991).
* [7] L. Jolliksen et. al, "Effects of the plate surface characteristics and gap height on yeldt intense of a magnetorheological fluid," _Sunar Mater. Struct._, vol.21, 11pp (2012).

Fig.1 The schematic and nomenclature of the proposed measurement platform.