Characteristic of pn Junction Formed in 4H-SiC by using Excimer-laser Processing in Phosphoric Solution







Motooka 744, Nishi-ku, Fukuoka, 819-0395, Japan

Phone: +81-92-802-3732

E-mail: ikeda@ed.kyushu-u.ac.jp

## 2 Experimental Setup

Figure 1 shows schematic illustration of the experimental setup for the investigation. The sample chip was placed in a glass petri dish filled with phosphoric acid solution at room temperature and irradiated with Krf excimer laser (Gigraphoton Inc.). Krf excimer laser was irradiated to n- or p-type epitaxial layer on n\({}^{*}\)-type 4H-SiC substrate.

The laser spot size was 150 \(\mu\)m \(\times\)550 \(\mu\)m. The laser fluence was 3.7\(\rightarrow\)4.3 J/cm\({}^{2}\). The duration time of the laser irradiation was 55 ns. The laser shot number was 10 or 100. p-type epitaxial layer was used to investigate pn junctions, while n-type epitaxial layer was used for SIMS and TEM investigation. The carrier concentration of n- or p-type layer was 1.0\(\times\)10\({}^{16}\) and 1.3\(\times\)10\({}^{17}\) /cm\({}^{3}\), respectively. The surface orientation of both the epitaxial layer was Si face; 4\({}^{\circ}\) off toward [1120].

## 3 Results and Discussions

### SIMS analysis

Figure 2 shows depth profiles of phosphorus measured with secondary ion mass spectroscopy (SIMS) for the irradiated areas of 10 laser shots and 100 laser shots. The measurement was carried out near the middle of each irradiated area. Comparison of these profiles indicates that the phosphorus concentration increases with increasing the laser shot number. Also, the phosphorus concentration has a maximum inside the SiC crystal. These results demonstrate doping of the SiC with phosphorus.

The phosphorus diffusion coefficient was known to be very small in 4H-SiC even at high temperature. The phosphorus diffusion coefficient has been reported to be 4.18\(\times\)10\({}^{19}\) cm\({}^{2}\)/s at 2200 \({}^{\circ}\)C [7], which suggests that negligible amount of diffusion takes place. However, as shown in Fig. 2, phosphorus concentration increases with increasing number of the laser shots. During the laser irradiations, the SiC surface might be heated up to near the SiC dissociation temperature (3100 K). Under such high temperature, laser-induced stresses due to the thermal expansion might generate significant amount of vacancies near the SiC surface. The generation of vacancies may cause in-diffusion of phosphorus at the surface.

### TEM analysis

Figure 3 shows TEM images at the SiC surface with the 100 laser shots. The periodic stripe pattern was clearly observed in the SiC. The stripe pattern corresponds to bilayer stacking sequence of the 4H-SiC [8]. The unit size of the periodic stripe is deduced to be 0.96 nm as indicated in Fig. 3. This size is almost same as the height of unit cell (1.008 nm) of the bilayer stacking structure [9]. As observed in Fig. 3, the periodic strip pattern is distorted near the SiC surface. It indicates that the bilayer stacking sequence was changed. It was reported that heavy nitrogen doping induced stacking faults in 4H-SiC [8]. Therefore, the stacking sequence modification observed in our sample could be possibly induced by large strain due to the heavy phosphorus doping.

### Hall effect

We also performed Hall effect measurements for the phosphorus doped region in the p-type layer by the van der Paurw method. Four tungsten probes were connected to the edges of the doped region. The injection current and magnetic field for the Hall effect measurements were 30 \(\mu\)A and +0.3 or -0.3 T, respectively. The Hall effect voltages were averaged using the values obtained at +0.3 and \(-\)0.3 T.

Results indicated the followings: The majority carriers at the phosphorus doped region are electrons. The carrier mobility is 295 cm\({}^{2}\)/ V s, which is in reasonable agreement with the value (\(\sim\)300 cm\({}^{2}\)/ V s) reported for n-type 4H SiC with 1\(\times\)10\({}^{18}\) /cm\({}^{3}\) doping [10]. The sheet carrier concentration is 2.25\(\times\)10\({}^{12}\) /cm\({}^{2}\). If we assume that the phosphorus doping depth is \(\sim\)30 nm from the SIMS results (Fig. 2), the carrier concentration is calculated to be 7.5\(\times\)10\({}^{17}\)/cm\({}^{3}\).

### I-V characteristics

Figure 4 shows I-V curves of the pn diodes as a parameter of the laser fluence. The measurement was performed in the manner shown in the inset of Fig. 4. Ohmic contact with the p-type layer was obtained by sputter deposition of Ti/Al followed by annealing at 1000 \({}^{\circ}\)C for 2 min in N\({}_{2}\) ambient. To measure I-V curves, tungsten probe is directly contacted to the phosphorus doped region.

The turn-on voltages of the diodes are smaller in comparison to that (-2\(\sim\)3 V) of conventional SiC pn-diode. The low turn-on voltages might be due to ultra-thin doped region as shown in the SIMS data (Fig. 2). Conventional SiC pn-diode has pn junction depth about few 100 nm. However, our pn junction depth is about \(\sim\)30 nm. This very shallow junction would induce increase in forward current due to decrease in the diffusion length of the injected hole from the p-type epitaxial layer to the phosphorus doped layer

### C-V characteristics

Figure 5 shows 1/C\({}^{2}\)-V curve for the depletion capacitance of the pn diode with reverse bias applying. The built-in potential of the pn junction and carrier concentration at the phosphorus doped region is deduced to be 2.9 V and 7.7\(\times\)10\({}^{17}\)/cm\({}^{3}\) by the 1/C\({}^{2}\)-V curve. By using the deduced carrier concentration, the Fermi level of the phosphorus doped layer is calculated to be 0.07 eV from the conduction band edge. The Fermi level of the p-type epitaxial layer is calculated from to be 0.12 eV above the valence band edge from the carrier concentration in the p-type layer. Therefore, the Fermi level difference is 3.01 eV, assuming that the band gap of the 4H-SiC is 3.2 eV. The Fermi level difference almost corresponds to the built-in potential deduced by extrapolation of the 1/C\({}^{2}\)-V curve.

### Reverse recovery characteristics

Figure 6 shows the reverse recovery characteristics of the pn junctions at the phosphorus doped regions. A pulsed voltage from -5 to +5 V was applied to the phosphorus doped region. The rise time of the pulsed voltage was about 20 ns. The reverse recovery time is about 800 ns for both the laser fluence (4.0, 4.3 J/cm\({}^{2}\)). This long recovery time is due to minority-carrier storage and indicates the formation of a pn junction.

## 3 Conclusion

Phosphorus is doped in the 4H-SiC by KrF excimer laser irradiation in phosphoric solution. The doping depth is as shallow as \(\sim\)30 nm. Stacking faults are observed at very near surface (within 10 nm) of the doped region. However, no amorphous region is observed at the doped region.

pn diodes are fabricated by the phosphorus doping in p-type epitaxial layer. The I-V curve shows a large on/off ratio over 7 orders of magnitude. The built-in potential (2.9 V) deduced from C-V measurement corresponds to the Fermi level difference between the phosphorus doped layer and p-type epitaxial layer. From these results, we conclude that the wet-chemical excimer-laser processing is a strong candidate for a new class of doping technology of SiC.

## Acknowledgment

The authors are grateful to Prof. Tatsuo Okada for his useful discussion and Takayuki Takao for his technical assistance. This work is supported in part by Grant-in-Aid for Scientific Research (No. 25289105).

