
B. Xu

Z. G. Wang

Y. H. Chen

P. Jin

X. L. Ye

H. Y. Liu

Z. Y. Zhang

G. X. Shi

C. L. Zhang

Y. L. Wang

F. Q. Liu


## 1 Introduction

In recent years, many research works have been devoted to the formation of strain-induced self-assembled quantum dots in lattice mismatched systems by Stranski-Krastanov (S-K) growth mode, due to their potential applications in nano-scale opto-electronic and microelectronic devices [1-2]. It is of great importance to control the growth process of the QDs, in order to get better structural and optical properties of the QD materials, such as QDs' size, density, emitting wavelength, optical quality, uniformity in size and ordering in location. In this paper, we present our work on the controlled molecular beam epitaxy (MBE)-growth of self-assembled In(Ga,Al)As/GaAs QDs, and their applications in light-emitting devices.

## 2 Techniques on Controlled Growth of Self-assembled Quantum Dots

We have studied the effects of various growth techniques on the structural and optical properties of self-assembled QDs. These techniques include the optimization of In deposition amount, In content in ternary alloy, QD growth temperature, QD growth rate, V/III ratio, and the adoption of seed layer, strained buffer layer, stain-reducing layer, as well as muti-QD-layer coupling. By these ways, the size, density, emitting wavelength and uniformity in size of the QDs can be fairly well controlled, and high-quality InAs/GaAs, InAlAs/AlGaAs /GaAs and InAs/InGaAs/GaAs QD materials can be obtained under optimum growth conditions.

### Effect of growth conditions

It has been proved that the size, density and uniformity of self-assembled QDs can be well controlled by optimizing the growth conditions, such as growth temperature, growth rate and arsenic pressure (V/III ratio).

Figure 1 shows the influence of As\({}_{4}\) pressure on InAs QD formation. The InAs QDs with a uniform size distribution and a relatively high density (7.5x10\({}^{10}\)/cm\({}^{2}\)) were formed under low As\({}_{4}\) pressure (Fig.1 (a)). As As\({}_{4}\) pressure increases, the diffusion of the In atoms

was hampered, leading to an increase in QD density and a decrease in QDs' size (Fig.1 (b) & (c)). The further increase of As\({}_{4}\) pressure will lead to the appearance and increase in density of super-large QDs (Fig.1 (d)), which represents the increasing chance for neighboring QDs merging into larger ones.

The influence of growth temperature on the density and size of InAs QDs is shown in Fig.2. The increase in growth temperature enhances surface diffusion length of the In atoms, which leads to a lower QD density and larger QD size (except the super-large ones).

According to the above conclusions, we often choose lower arsenic pressures and higher substrate temperatures for better structural and optical properties of QD-LD materials.

### Effect of special structures

By special design of the QD material structures, using seed layer, strained buffer layer, stain-reducing layer and muti-QD-layer coupling, we can further control the properties of self-assembled QDs.

Figure 3 demonstrates the strain coupling of an InGaAs QD layer and an InGaAs

Fig. 2: AFM images of 2.2ML InAs QDs grown under As\({}_{4}\) pressure of 5.0\(\times\)10\({}^{-6}\) Torr and at growth temperature of (a) 460\(\,\mathrm{\SIUnitSymbolCelsius}\), (b) 480\(\,\mathrm{\SIUnitSymbolCelsius}\) and (c) 500\(\,\mathrm{\SIUnitSymbolCelsius}\).

Fig. 1: AFM images of 2.2ML InAs QDs grown at 480\(\,\mathrm{\SIUnitSymbolCelsius}\) under arsenic pressure (As\({}_{4}\)) of (a) 2.5\(\times\)10\({}^{-6}\) Torr, (b) 5.0\(\times\)10\({}^{-6}\) Torr, (c) 1.0\(\times\)10\({}^{-5}\) Torr and (d) 2.0\(\times\)10\({}^{-5}\) Torr.

QD layer. The adoption of InGaAs QD seed layer can enhance the density of the InGaAs QD layer from 2.5x10\({}^{10}\)/cm\({}^{2}\) to 1.1x10\({}^{11}\)/cm\({}^{2}\) (Fig.3 (a) & (b))[3]. Cross-sectional TEM of the sample (Fig.3 (c)) clearly shows the vertical coupling between the two QD layers. Adopting seed layer can not only increase the QDs' density, but also improve their uniformity, which can be revealed by the narrowing of the PL FWHM from 62.2meV for the single InGaAs QD layer to 43.7meV for the InGaAs QD layer grown on InGaAs QD layer (Fig.4). This technique is very useful for QD-LD structures, where high QD density and uniformity are expected.

Usually InGaAs quantum wells (QWs) and In(Ga)As QDs on GaAs substrates can emit at a wavelength no longer than 1.2m. By the adoption of stain-reducing layer (SRL) or dot-in-well structure, the emitting wavelength of GaAs-based In(Ga)As QDs can be extended to more than 1.3m, favoring the fabrication of 1.3m QD-LD on GaAs substrate. However, the energy separations between ground and first excited states in these structures tend to be small, resulting in low characteristic temperature of the QD-LDs. So we use a combined InAlAs/InGaAs SRL on InAs QDs [6]. The Al-containing layer can block the carrier escape from the QDs, leading to an energy separation of more than 100meV between ground and first excited state, and an emission wavelength up to 1.35m (Fig. 5).

It is found that InAs QDs with InAlAs/InGaAs SRL can withstand higher annealing temperatures than with InGaAs SRL[7], which is very important for the growth of 1.3mQD-LD structures where higher growth temperature is expected to improve the quality of the AlGaAs cladding layer. Figure 6 demonstrates the difference in thermal stability between InAs QDs covered by InGaAs SRL and InAlAs/InGaAs SRL during rapid thermal annealing. The QD emission peaks start blue-shifting from annealing temperature of 650\({}^{\circ}\)C for the InGaAs SRL case, which results from the In-Ga intermixing between InAs QDs and surrounding Ga-containing layers. While for the InAlAs/InGaAs SRL case, the blue-shift starts from 700\(\sim\)750 \({}^{\circ}\)C. This is believed to come from the fact that the Al atoms in InAlAs layer can considerably reduce the In-Ga inter-mixing at higher temperatures[6, 7], due to the strong bonding energy between Al-In and Al-Ga atoms.

## 3 Application of High-quality Quantum-dot Materials in Light-emitting Devices

On basis of the above works, various materials for opto-electronic devices, such as high-power, long-life QD-LDs emitting near 1\(\upmu\)m, QD-LDs emitting in red-light range, 1.3\(\upmu\)m QD-LDs on GaAs substrate and QD-SLDs, have successfully been achieved by us.

### High-power QD-LD with long lifetime

We have grown high-power QD-LD materials with five layers of coupled InAs QDs in the active region. The QD-LDs exhibit a lasing wavelength near 1080nm, a peak power of 3.6W from both facets, a threshold current density of 220A/cm\({}^{2}\) and a quantum slope efficiency of 84.6% in continuous-wave (CW) mode at room temperature (Fig. 7).

We introduced an InGaAs SRL on the InAs QDs, and the corresponding QD-LD demonstrates a rather long lifetime of several thousands of hours at 1W output power from both facets. A comparative investigation indicates that the lifetime of QD-LDs with InGaAsSRL is much longer than that of QD-LDs without any SRL[4]. The improved lifetime can be explained by the reduction of strain in and around InAs QDs by the SRL, which leads to a suppression of crystal defects.

### QD-LD emitting in red-light range

QD-LDs materials emitting in red-light range have been fabricated with InAlAs QDs in AlGaAs matrix in the active region. The growth temperature has been optimized to be 560\({}^{\circ}\)C, where the QDs show a stronger PL intensity and narrower spectral width, indicating a better optical quality and QD uniformity (Fig. 8 (a)).

The corresponding LDs can lase in CW mode at low temperatures (up to 220K), with a threshold current density around 410A/cm\({}^{2}\) and lasing wavelength near 700nm. At room temperature, the QD-LD can lase in pulsed mode at 725nm from the ground-state transition (Fig. 8 (b)) [5].

### QD-Sld

The inhomogeneous size distribution of QDs, which broadens the emission spectrum, is disadvantageous for QD-LDs. However, it becomes an intrinsic advantage for designing super-luminescent diodes[8].

Figure 8: (a) Low-temperature PL spectra of In\({}_{0.65}\)Al\({}_{0.35}\)As/ Al\({}_{0.35}\)Ga\({}_{0.65}\)As QDs grown at 530 and 560\({}^{\circ}\)C. AFM images for uncapped QDs (1\(\upmu\)m x 1\(\upmu\)m) are shown in the insets. (b) Room-temperature electro-luminescence spectra in pulsed mode of the InAlAs/AlGaAs QD-LDs below and above threshold.

Figure 7: Laser power from both uncoated facets vs. injection current for a QD-LD at room temperature in continuous wave mode. The inset shows a cross-sectional TEM image of the LD’s active region.

By inclining the injection stripe from the length direction of the cavity of the devices, we have fabricated QD-SLDs from materials similar to those of QD-LD. The devices can work in CW mode at room temperature. Output power as high as 200mW is achieved at 1.4A for an 100\(\upmu\)m x 1600\(\upmu\)m wide device, whose emission spectrum width is 60meV (Fig. 9). The performances of the QD-SLDs can be further improved by optimizing the QD structure in the active region.

## 4 Summary

High quality self-assembled QDs have been obtained under optimum growth conditions. The effects of arsenic pressure, growth temperature and seed-layer are clearly demonstrated. Based on the above nano-structures, long-life and high-power QD lasers emitting near 1 \(\upmu\)m, red-emitting QD lasers, and long-wavelength GaAs-based QD laser with InAlAs covering layers have successfully been fabricated.

Acknowledgement to the financial support by Special Funds for Major State Basic Research Project of China (No. G2000068303), National Natural Science Foundation of China (No. 60390071, 60276014, 90101004, 90201033), and National High Technology Research and Development Program of China (No. 2002AA311070, 2002AA311170) in this work.

