Development of Bi-Axial Tensile Tester to Investigate Yield Locus for Aluminum Film Under Multi-Axial Stresses

Y. Nagai\({}^{1}\)

 T. Namazu\({}^{1}\)

 N. Araki\({}^{1}\)

 Y. Tomizawa\({}^{2}\)

 and S. Inoue\({}^{1}\)

\({}^{1}\) Department of Mechanical and Systems Engineering, University of Hyogo

2167 Shosha, Himeji, Hyogo 671-2201, Japan: namazu@eng.u-hyogo.ac.jp (T. Namazu)

\({}^{2}\) Mechanical Systems Laboratory, Corporate Research & Development Center, Toshiba Corporation

1 Komukai-Toshiba-cho, Saiwai-ku, Kawasaki, Kanagawa 212-8582, Japan

###### Abstract

This paper describes novel biaxial tensile test technique for a film specimen to investigate material responses to uniaxial and biaxial tensile forces. We have developed biaxial tensile tester that consists of four sets of actuator, load cell, and displacement meter in order to apply an arbitrary amount of tensile force to a film specimen in each axis. With the uniaxial test specimen of sputtered Al film, average Young's modulus of 35 GPa and yield strength of 115 MPa have been obtained. With the biaxial test specimen, evaluation of the yield locus for Al film has carried out by applying biaxial stresses with various strain rate ratios. The obtained yield stresses could be fitted by the yield criterion based on Logan-Hosford equation. This indicates that the flow stress under biaxial stress condition differ from that under uniaxial condition. Information about the yield locus would be useful for the structural design of MEMS including Al film structures subjected to biaxial stresses.

978-1-4244-1793-3/08/S25.00 02008 IEEE 978-1-4244-1793-3/08/S25.00 02008 IEEE 978-1-4244-1793-3/08/S25.00 02008 IEEE

## 1 Introduction

Many kinds of metallic films, such as sputtered Al and electroplated Ni films, are often employed as structural materials in MEMS. Most of these metallic structures are subjected to not only uniaxial but also multi-axial stresses. Understanding of mechanical behavior of these materials under multi-axial stress condition in addition to uniaxial one is important for the design of MEMS.

For characterization of a film material, the uniaxial tensile test is popular. Several types of the test techniques have been so far proposed to accurately measure mechanical properties, such as Young's modulus, Poisson's ratio, and yield strength [1]. The uniaxial tensile test is, of course, useful, but is restricted to providing only uniaxial material information. However, the biaxial tensile test for a film specimen is scarce due to technical difficulties in accurately controlling biaxial stresses and displacements of the specimen. To reliably design metallic microstructures in MEMS, material characterizations under multi-axial stress conditions are necessary and an appropriate constitutive criterion that can precisely describe elastic and plastic deformation behavior should be developed.

The objective of this study is to develop the biaxial tensile test technique for a film specimen. This paper focuses on evaluating the yield locus for Al film deposited by sputtering. The uniaxial tensile test of Al film has been firstly conducted in order to check the ability of the tester for measuring a stress-strain relation of a film specimen. Then the biaxial tensile test of Al film has been performed to investigate the yield locus that is the significant material information necessary for the structural design of MEMS.

## 2 Experimental Procedure

### Specim

Fig. 1 illustrates the designed specimens for uniaxial and biaxial tensile tests. The specimens consist of an Al film specimen section with gauge marks, Si springs, chucking holes and frame. To obtain force-displacement relation of Al film, the tensile tests are performed twice a specimen. In the first test, both Al film and Si spring is tensioned simultaneously. After fracture of Al film, only Si spring is tensioned as the second test. Consequently, force-displacement relation of only Al film can be obtained by subtracting that of Si spring from the sum of Al film and Si spring [2]. This method enables us to achieve the biaxial tensile test of a film specimen.

Fig. 2 illustrates a process chart for fabricating the biaxial tensile test specimen. A silicon wafer was used as a starting material. Al film was deposited onto the top surface by sputtering, and then was patterned to a specimen shape. After fabrication of hooking holes by D-RI

Fig. 1: Schematic of uniaxial and biaxial test specimens.

Fig. 2: Fabrication process of biaxial tensile test specimen.

etching mask was removed. Through these processes, three types of specimens were prepared as shown in Fig. 3. The Type A specimen is designed for the uniaxial tensile tester developed previously [3]. The Type B and C specimens are designed for the biaxial tensile tester described in the next section.

#### 4.2.2 Biaxial Tensile Tester

Fig. 4(a) shows the developed biaxial tensile tester. The tester consists of a PZT actuator, a load cell, a linear variable differential transformer (LVDT), a specimen holder, and an actuator case. The case includes the levers for amplification of PZT actuator's displacement to 3.85-fold. As shown in Fig. 4(b), four sets of these equipments are mounted into the case, and the two sets are utilized in an axis. The same amount of tensile force is applied to a specimen from both the ends in each axis, so that the center position of the specimen does not move regardless of tensile force. The tester is settled on a vibration isolation system, as shown in Fig. 5, to avoid any mechanical vibrations during testing.

Fig. 6 depicts displacements of the PZT actuators and the specimen hooking holders in supplying voltages to the actuators. Displacement-voltage relations in all the channels are found to be almost linear. In channel 1 (CH-1), the maximum displacement of the specimen holder is approximately 100 \(\upmu\)m, which is 3.85 times that of the PZT actuator. Other channels have the same abilities of displacement amplification as CH-1.

## 5 Results and Discussions

### Uniaxial Tensile Test Results

Fig. 7 shows representative tensile force-displacement diagram of the Type B specimen evaluated using CH-1 and CH-3 in the biaxial tensile tester. The open plots and solid lines are indicative of force-displacement relation with and without Al film, respectively. Force-displacement relations with Al film have non-linear regions before film failure, whereas those without the film are linear. The non-linear behavior represents that plastic deformation has occurred in the film.

Typical tensile stress-strain curves of Al film are shown in

Figure 3: The produced specimens for tensile tests.

Figure 6: Result of displacement measurements.

Figure 5: The biaxial tensile test system.

Fig. 8. The open and closed plots indicate the results with the Type B and A specimens, respectively. The uniaxial tensile tester developed previously has been employed to test the Type A specimen [3]. The obtained Young's modulus of Type B is found to be 33.2 GPa, which agrees with that of Type A. The yield stress of Type B is 105.8 MPa, also comparable to that of Type A. These similarities in the mechanical characteristics obtained by the biaxial and uniaxial tensile testers exhibit that the existence of Si springs in the Type B specimen does not affect the accuracy of the mechanical property derivation of Al film, and both the testers possess an excellent accuracy of the stress and strain measurements.

**Biaxial Tensile Test Results**

Figs. 9 show typical tensile force-displacement curves of the Type C specimens. These results were obtained by the biaxial tensile tests under the tensile strain rate ratios of (a) 1:1 and (b) 1:0.25 in \(x\) (CH-1 and 3) and \(y\) (CH-2 and 4) coordinates at R.T. In the case of the uniform strain rate test shown in Fig. 9(a), force-displacement relations in \(x\)-axis are very similar to those in \(y\)-axis. The relations with Al film include a non-linear region originating from plastic deformation as with the uniaxial test result. After the film failure, the relations are linear. In the non-uniform strain rate test shown in Fig. 9(b), force-displacement curves with Al film in \(x\)-axis are different from those in \(y\)-axis. For each test, the critical forces at yield point of Al film can be measured in each channel. To estimate the yield stresses of Al film under biaxial stresses, finite element analyses (FEAs) have been

Fig. 8: Tensile stress-strain curves of the Type A and B specimens obtained by uniaxial tensile tests. The tests of the Type A and B specimens were carried out using the uniaxial and biaxial tensile tester, respectively.

Fig. 10: Stress distributions on Al film under biaxial tensile forces derived from finite element analyses.

Fig. 7: Tensile force-displacement curves of the Type B specimen obtained by uniaxial tensile test.

Fig. 9: Tensile force-displacement curves of the Type C specimen obtained by biaxial tensile tests.

performed. Fig. 10 shows stress distributions of \(\sigma_{xx}\) and \(\sigma_{yy}\) at the film specimen section of the FEA model. The applied tensile forces at each axis were the critical forces at yield point of Al film based on the biaxial tensile tests. The measured value of Young's modulus by uniaxial tensile test was used as a material constant in FEAs. FEA results represent that stress distributions are not uniform because stress concentration has occurred nearby a fillet section. In this study, we have defined the biaxial yield stress as the stress at the center of the film section when the critical forces in each axis were applied [4].

Fig. 11 shows the yield locus obtained by performing the biaxial tensile tests under various strain rate ratios. The dashed, dotted, and solid lines indicate the estimation lines based on the equations of Tresca, Hill, and Logan-Hosford, respectively, which are given as follows:

\[\sigma_{uni}=\sigma_{\max}-\sigma_{\min}=\sigma_{xx} \tag{1}\]

\[\sigma_{uni}^{2}=\sigma_{xx}^{2}+\sigma_{yy}^{2}-\frac{2R}{1+R}\sigma_{xx} \sigma_{yy} \tag{2}\]

\[\sigma_{uni}^{8}=\frac{1}{1+R}\Big{(}\sigma_{xx}^{8}+\sigma_{yy}^{8}\Big{)}+ \frac{R}{1+R}\Big{(}\sigma_{xx}-\sigma_{yy}\Big{)} \tag{3}\]

where \(\sigma_{uni}\) is the yield stress under uniaxial stress, \(\sigma_{xx}\) and \(\sigma_{yy}\) are the yield stresses in each axis under biaxial stresses, and \(R\) is the plastic strain ratio of thickness to width directions in a specimen. The estimated yield stresses under biaxial stresses state exhibit the close values to the yield stress under uniaxial stress state. The yield locus for Al film is fitted by using Logan-Hosford equation with \(R\)-value of 0.5; therefore, the yield stress of Al film under various biaxial stress states can be predicted using the equation.

## 4 Conclusions

We have designed and developed the biaxial tensile tester to evaluate mechanical characteristics under uniaxial and biaxial stress conditions. First, the uniaxial tensile tests of Al film deposited by sputtering were carried out. Mechanical characteristics measured by the newly developed biaxial tensile tester were in good agreement with those by the uniaxial tensile tester developed previously. Then, the biaxial tensile tests were performed. The tests enabled us to obtain the yield locus for Al film under biaxial stresses. The measured yield stresses under uniaxial and biaxial stress states showed the similar values, and the stresses could be fitted by using the Logan-Hosford equation. The yield locus for Al film would be useful for the reliable structural design of MEMS with Al film structures.

## Acknowledgements

The authors would like to thank members of Center for Semiconductor Research & Development, Toshiba Corporation Semiconductor Company and also members of Corporate Manufacturing Engineering Center, Toshiba Corporation, for sample preparation and fruitful discussion on this study. Also, the authors would like to express their gratitude to Prof. G. Hashiguchi of Shizuoka University and Ms. N. Koda of Kagawa University, for extensive discussion on the sample fabrication techniques.

## References

* [1] T. Namazu and S. Inoue, "Characterization of Single Crystal Silicon and Electroplated Nickel Films by Uniaxial Tensile Test with in-situ X-ray Diffraction Measurement", _Fract. & Fati. Eng. Mater. & Struct._, Vol. 30, No. 1, pp. 13-20, 2007.
* [2] K. Sato and M. Shikida, "Micro Tensile-Test System Fabricated on A Single Crystal Silicon Chip", _Proc. MEMS 1996_, pp. 360-364, 1996.
* [3] T. Namazu, S. Inoue, D. Ano, and K. Koterazawa, "Direct Measurement Technique of Strain in XRD Tensile Test for Evaluating Poisson's Ratio of Micron-Thick TiN Films", _Proc. MEMS 2004_, pp. 157-160, 2004.
* [4] T. Naka, Y. Nakayama, T. Uemori, R. Hino, and F. Yoshida, "Effects of Temperature on Yield Locus for 5083 Aluminum Alloy Sheet", _J. Mater. Proc. Technol._, Vol. 140, pp.494-499, 2003.

Fig. 11: Yield locus for sputtered Al film measured by biaxial tensile tests under various tensile strain rate ratios. The yield stress under biaxial stresses is slightly different from that under uniaxial stress. These yield stress data could be fitted by using the yield equation of Logan-Hosford with \(R\)-value of 0.5.