
Guy L. Whitworth

1 Department of Physics and Astronomy, University of St Andrews, KY16 9SS, UK

 Pavlos P. Manousiadis

1 Department of Physics and Astronomy, University of St Andrews, KY16 9SS, UK


1 Department of Physics and Astronomy, University of St Andrews, KY16 9SS, UK


1 Department of Physics and Astronomy, University of St Andrews, KY16 9SS, UK

 Graham A. Turnbull

1 Department of Physics and Astronomy, University of St Andrews, KY16 9SS, UK

 Ifor D. W. Samuel

1 Department of Physics and Astronomy, University of St Andrews, KY16 9SS, UK

## 1 Method

Conjugated polymer solutions were deposited onto glass slides pre-treated with an adhesion promoter via spin coating to create light-emitting thin films. Drops of a weakly interacting solvent like acetone were then placed on top of the film converting it into a surface 'gel'; malleable and deformable.

The films were then nanoimprinted using a perfluoropolyether MD700 soft stamp. The soft stamps were cast from silicon master gratings made by e-beam lithography and reactive ion etching. The soft stamps were pressed into the surface gel (made out of the polymer film and infiltrated acetone) using an EVG photomask aligner with custom nanoimprint tooling at a constant uniform pressure. During contact acetone could leave the polymer film through the MD700 stamp. After a time of at least 5 seconds the stamp was separated from the polymer film, with the reciprocal copy of the soft stamp grating imprinted into the surface.

## 2 Results

Scanning electron microscopy (SEM) and atomic force microscopy (AFM) images revealed high fidelity gratings made out of conjugated polymers such as poly(9,9-dioctylfluoreryl-2,7-diyl) (PFO) and poly[2,5-bis(2'-ethylhexyloxy)phenyl)-p-phenylcynylene] (BBEHP-PPV). Grating depths achieved were up to 80 nm in BBEHP-PPV and 25 nm in PFO with lateral feature sizes as low as 70 nm.

For BBEHP-PPV films, surface emitting DFB gratings were imprinted with a lattice constant of 350 nm. This was engineered to satisfy the Bragg equation \(m\lambda=2\pi n_{eff}\) at the peak gain of the polymer, where m is the diffractive order, \((\mathrm{m}-2\) for surface emitting DFB\(\mathrm{s})\), \(\lambda\) is the feedback wavelength and \(n_{\mathrm{eff}}\) is the effective refractive index of the waveguide mode. When this condition is met we can achieve second order DFB

Figure 1: The SIIL process a) before and b) after the imprinting.

lasing in BBEHP-PPV fabricated via SIII. The output of such a laser is shown in figure 2, where we observed narrow linewidth (\(\sim\)0.1 nm) lasing centred at 533.7 nm with a threshold of 4 kW/cm\({}^{2}\).

Organic DFB lasers can then be used as explosive sensors [4], with SIIL providing an efficient and scalable production for disposable devices. As well as DFB lasers, directional emitters have been fabricated and optimised through grating design. These devices have been used to improve transmitters for visible light communications.

## 7 Conclusions

In conclusion, we have presented a technique for direct microstructuring of conjugated polymer films. Once structured a polymer film can be used in a wide variety of devices such as an explosive sensing laser or as data transmitters and receivers in visible light communications. The SIIL process allows devices to take advantage of high diffraction efficiencies at the air interface and also to be made in an easy, one-step scalable manner.

