
in Modern Power Systems


\({}^{*}\) Warsaw University of Technology, Institute of Electrical Power Engineering, Warsaw, Poland, e-mail:


\({}^{\dagger}\) APS Energia Sp. z o.o., Zielonka, Poland, e-mail: _andrzej.jasinski@apsenergia.pl_

## I Information

This is an industrial paper. Please contact the authors for more information.