# Research on Bioengineering Algorithm based on Dynamic Fuzzy Neural Network

Gong Xiaofang

Meiga polytechnic Institute Hubei,

Hubei,432017,China gongxiaofang@408@163.com

###### Abstract

Dynamic Fuzzy Neural Network (DFNN) is an extension of Fuzzy Neural Network (FNN). It combines the advantages of fuzzy logic and neural network to deal with uncertainty and fuzziness.In recent years, with the rapid development of bioengineering, the application of dynamic fuzzy neural network in the field of bioengineering has been paid more and more attention. This paper will focus on the impact and prospect of dynamic fuzzy neural network on bioengineering.

 dynamic fuzzy neural network; bioengineering; Convolutional neural networks +
Footnote †: publicationtext: **979-8-3-5033-1912-5/23/331.00 ©2023 IEEE**

## I Introduction

Bioengineering is a high-tech discipline that involves the intersection of disciplines[1], which integrates engineering, chemistry, biology and other disciplines to develop new technical tools and methods using the basic laws and biological properties of biological systems to develop more efficient, sustainable and environmentally friendly production methods[2]. Dynamic Fuzzy Neural Network (DFNN) is a new type of neural network algorithm, which has a wide range of application prospects in the field of bioengineering. This paper will analyze and discuss the foundation of DFNN, the current situation of bioengineering and the impact of DFNN on bioengineering.

### _The foundation of DFNN_

#### I-A1 DFNN overview

DFNN is a combination of fuzzy systems and neural networks, which uses fuzzy components to capture the fuzzy nature of input variables, while processing these fuzzy components through the learning ability of neural networks[3]. DFNN consists of three main parts: input, output, and membership function. Among them, the input and output are processed by the neural network, and the membership function is a mathematical function based on fuzzy logic[4].

#### I-A2 Advantages of DFNN

DFNN has a variety of advantages, including nonlinear modeling and approximation capabilities, ability to handle fuzzy and uncertain information, fast training speed and adaptability. Compared with other neural network algorithms, DFNN has obvious advantages in the field of high-dimensional data processing and fuzzy control[5].

### _Current status in the field of bioengineering_

Research in the field of bioengineering involves many fields, such as medicine, ecology, environmental protection, agriculture, etc[6]. At present, many important research results have been achieved in the field of bioengineering. For example, chondro-based bioscaffolds for liver regeneration, glucagon-like peptide-1 receptor agonists for inhibiting obesity and diabetes, DNA barcoding technology for identifying counterfeit drugs, etc[7].

### _Impact of DFNN on bioengineering_

#### I-C1 Biomedical Engineering

Biomedical engineering is a discipline that brings together engineering, biology, and medicine. Biomedical engineering focuses on how to apply modern engineering techniques and methods to solve difficult problems in the medical field[8]. The application of DFNN in the field of biomedical engineering is mainly reflected in how to achieve more accurate and efficient disease diagnosis and treatment.

#### I-C2 Ecological and environmental engineering

Ecological environmental engineering is an engineering discipline that studies how to protect and improve the environment, which mainly focuses on industrial and urban emissions, land use, water resources management, etc. DFNN can be applied to the monitoring, migration and prediction of pollutants, providing a more accurate means for environmental protection[9].

#### I-C3 Agricultural bioengineering

Agricultural bioengineering is a discipline that uses biotechnology and bioengineering to improve agriculture. DFNN can use fuzzy control theory to deal with multiple factors including light, temperature, humidity, etc., to help agriculture achieve fully automated production[10].

#### I-C4 Food Engineering

Food engineering is an engineering discipline that studies how biotechnology can be used to produce and improve food. DFNN can quickly and accurately analyze and optimize the ratio of ingredients by establishing a data model of a large number of food raw materials and nutrients, and improve food quality and production efficiency[11].

## II Related concepts

### _Mathematical description of a dynamic fuzzy neural network_

In bioinformatics, dynamic fuzzy neural network can be used for gene sequence analysis, protein structure prediction and other tasks. By fuzzy processing of gene sequences, dynamic fuzzy neural network can identify gene patterns related to diseases, which provides powerful support for disease diagnosis and drug design. is shown in Equation (1).

\[\mathit{tole}^{i\theta}(y_{i}\cdot x_{y_{i}})=y_{y_{j}}\geq\max(x_{y_{j}}) \tag{1}\]In the field of biomedical imaging, dynamic fuzzy neural network can be used for image processing and diagnosis is shown in Equation (2).

\[\max(x_{y})=(x_{y}^{\ 2}+6)\frac{\pi}{2}\ mean(\sum x_{y}) \tag{2}\]

Through fuzzy processing and feature extraction of medical images, dynamic fuzzy neural network can identify lesion areas and improve the accuracy and reliability of medical diagnosis as shown in Equation (3).

\[M(b_{i})=\sum x_{i}\bigcap\varphi\rightarrow\oint y_{i} \tag{3}\]

### _Selection of algorithm research schemes_

Dynamic fuzzy neural network can deal with uncertainty and fuzziness, and has strong adaptive ability and fault tolerance as shown in Equation (4).

\[f(x_{i})=z_{i}\cdot\prod M(b_{i})-w_{i} \tag{4}\]

By taking the output of biosensors as input, the dynamic fuzzy neural network can automatically identify the target substances, and provide technical support for environmental monitoring and food safety as shown in Equation (5).

\[f(x_{i})+M(b_{i})\leq\max(x_{y}) \tag{5}\]

In addition, the dynamic fuzzy neural network has good robustness and generalization ability, and can deal with complex nonlinear problems. are shown in Equation (6).

\[\overline{f(x_{i})+M(b_{i})}\leftrightarrow mean(\sum x_{y}) \tag{6}\]

### _Analysis of algorithm research schemes_

Dynamic fuzzy neural network also has some challenges and limitations. For example, there may be a local minimum problem in the training process are shown in Equation (7).

\[No(x_{i})=\overline{\overline{f(x_{i})+M(b_{i})}} \tag{7}\]

Lack of clear guiding principles for parameter adjustment and selection; The processing efficiency of large-scale data sets needs to be improved is shown in Equation (8).

\[Zh(x_{i})=\min[\sum\overline{f(x_{i})+M(b_{i})}] \tag{8}\]

Optimize algorithm and model structure: Study more efficient training algorithm and model structure to improve the performance of dynamic fuzzy neural network as the formula (9).

\[accur(x_{i})=\frac{\min[\sum\overline{f(x_{i})+M(b_{i})}]}{\sum\overline{f(x_{ i})\oplus M(b_{i})}}\times 100\% \tag{9}\]

Multi-modal data processing: Combining various data modes (such as text, image, video, etc.) to expand the application field of dynamic fuzzy neural network in bioengineering can be expressed as formula (10).

\[accur(x_{i})=\frac{\min[\sum\overline{f(x_{i})+M(b_{i})}]}{\sum\overline{f(x_{ i})\oplus M(b_{i})}}\times 100\%+random(x_{i}) \tag{10}\]

Interpretability and transparency: Improve the interpretability and transparency of dynamic fuzzy neural network, and make its decision-making in bioengineering more reliable and credible.

## III Optimization strategies for bioengineering

The dynamic fuzzy neural network adopts the random optimization strategy for bioengineering and adjusts the bioengineering parameters to realize the scheme optimization of bioengineering. Dynamic fuzzy neural networks are divided into different algorithm research levels for biological engineering, and different schemes are randomly selected. In the iterative process, the algorithm research schemes of different algorithm research levels are optimized and analyzed. After the optimization analysis is completed, the algorithm research level of different schemes is compared, and the best bioengineering algorithm research scheme is recorded.

## IV Practical examples of bioengineering

### _Introduction to algorithm research_

Large-scale data processing: Optimize algorithms and computing resources to improve the ability of dynamic fuzzy neural network to process large-scale data is shown in Table I.

The algorithm research process in Table I. is shown in Figure I.

Explore more application scenarios of dynamic fuzzy neural network in bioengineering, such as biopharmaceuticals and agricultural biotechnology.

Fig. 1: Algorithm research analysis process for bioengineering

### _Bioengineering situation_

Strengthen the cross-cooperation of bioengineering, computer science, mathematics and other disciplines to jointly promote the research and application of dynamic fuzzy neural network in bioengineering field was shown in Table II.

### _Stability of algorithm studies in bioengineering_

When using dynamic fuzzy neural network to process biological data, it is necessary to consider the issues of ethics and privacy protection to ensure the safety and compliance of data.

Establish a standardized evaluation system of dynamic fuzzy neural network to promote the comparison and communication between different studies is shown in Table III.

As a new computational model, Dynamic Fuzzy Neural Network (DFNN) has a wide application potential in bioengineering. Through the application of fuzzy processing and learning of gene expression data, protein structure prediction and drug design and screening, dynamic fuzzy neural network can improve the accuracy and reliability of data processing and analysis in bioengineering, and provide more support and help for the development and application of bioengineering.

Dynamic Fuzzy Neural Network (DFNN) can transform the uncertainty and fuzziness of the data in the process of drug design into a fuzzy set that can be processed, and use neural network to learn the complex patterns and correlation in the process of drug design, so as to improve the effect and efficiency of drug design and screening.

## V Conclusion

Dynamic fuzzy neural network still faces some challenges and problems in bioengineering. Firstly, due to the complexity and large-scale of biological data, the training and reasoning process of dynamic fuzzy neural network may be very complicated and time-consuming. Secondly, how to choose and design fuzzy function and network structure reasonably is also an important problem. In addition, for different types of biological data, it may be necessary to design different dynamic fuzzy neural network models to adapt to their characteristics and needs. Therefore, it is necessary to further study and improve the algorithms and methods of dynamic fuzzy neural networks in order to better apply them to various problems and tasks in bioengineering.

## Acknowledgements

Thanks for the support of the planning guidance project of the Hubei Provincial Department of Housing and Urban-Rural Development and the scientific research planning guidance project of the Hubei Provincial Department of Education.

## References

* [1] Aissiou, A. K., Jha, S., Dhunnoo, K., Ma, Z., Li, D. X., Ravin, R., Kunze, M., Wong, K., & Adelesia, A. B.(2023) Transcriptomic response of bioengineering human cartilage to parabolic flight microgravity is sex-dependent. Npj Microgravity, 9(1).
* [2] Almeida, G., Iglesia, R. P., Rinaldi, J. D., Murai, M. K., Calomeno, C., da Silva, L. N., Hovatta-Pereira, D. B., Dinh, L. B. M., Miglino, M. A., & Carreira, A. C. (2023) Current Trends on Bioengineering Approaches for Ovarian Microenvironment Reconstruction. Tissue Engineering Part B-Reviews, 29(3): 260-298.
* [3] Aneesh, E. M., Anoopkumar, A. N., Madhavan, A., Sindhu, R., Binod, P., Kududus, M., Ruiz, H. A., Pandey, A., Awasthi, M. K., & Show, P. L.(2023) Inferences on bioengineering perspectives and circular economy to tackle the emerging pollutants. Environmental Technology & Innovation, 30.
* [4] Barabadi, H., Noqani, H., Ashouri, F., Prasad, A., Jounaki, K., Mobaraki, K., Mohanta, Y. K., & Mostafari, E.(2023) Nanobiotechnological approaches in anticoagulant therapy: The role of bioengineered silver and gold nanomaterials. Talanta, 256.

Fig. 3: Bioengineering quality of dynamic fuzzy neural network algorithm research

Fig. 2: Bioengineering quality of different algorithms* [5] Behbahnipour, M., Benedi, R., Navarro, S., & Ventura, S.(2023) OligoBinders: Bioengineered Soluble Amyloid-like Nanoparticles to Blind and Neutralize SARS-CoV-2. Ase Applied Materials & Interfaces.
* [6] Bellazzi, R., Cecconi, M., Costantino, M. L., & Veltri, P.(2023) Bioengineering and medical informatics education in MD programs: perspectives from three Italian experiences. International Journal of Medical Informatics, 172.
* [7] Carter, L., Mankad, A., & Hobman, E. V,(2023) Is Public Engagement in Bioengineering and Synthetic Biology Improving Research Outcomes? Omics-a Journal of Integrative Biology, 27(2): 47-50.
* [8] Contreras, M. P., Pai, H., Selvaraj, M., Toghani, A., Lawson, D. M., Tuntas, Y., Duggan, C., Yuen, E. L. H., Stevenson, C. E. M., Harant, A., Maqbool, A., Wu, C. H., Bozkurt, T. O., Zmoun, S., & Dervanin, L.(2023) Resurrection of plant disease resistance proteins via helper NLR bioengineering. Science Advances, 9(18).
* [9] Dancourt, J., Piovesan, E., & Lavieu, G.(2023) Efficient cell death mediated by bioengineered killer extracellular vesicles. Scientific Reports, 13(1).
* [10] Deich, C., Gaut, N. J., Sato, W., Engelhart, A. E., & Adamala, K. P,(2023) New Sequence Fluorescent Proteins for Cell-Free Bioengineering. Acs Synthetic Biology, 12(4): 1371-1376.
* [11] Deng, H. P., Zhang, A., Pang, D. R. R., Xi, Y. S., Yang, Z. H., Matheson, R., Li, G. P., Luo, H., Lee, K. M., Fu, Q., Zou, Z. L., Chen, T., Wang, Z., Josales, I. A., Peters, C. W., Yang, J. B., Coronel, M. M., Yolcu, E. S., Shiwari, H., Garcia, A. J., Markmann, J. F., & Lei, J.(2023) Bioengineered mental transplant site promotes pancreatic islet alografts survival in non-human. Cell Reports Medicine, 4(3).
* [12] Erbay, I. H., Polatli, E., Koe, A. C., Ozbilgic, R., Karaman, O., & Guven, S.(2023) Bioengineering Bone-on-a-Chip Model Harnessing Metabolise and Osteoclastic Resolution. Advanced Engineering Materials, 25(6).
* [13] Fiorillo, L., Meto, A., & Ciccin, M.(2023) Bioengineering Applied to Carl Implantation, a New Protocol: "Digital Guided Surgery". Prosthesis, 5(1): 234-250.
* [14] Gao, Y. X., Bate, T. S. R., & Callanan, A.(2023) A Unification of Nanotopography and Extracellular Matrix in Electrospun Scaffolds for Bioengineered Hepatic Models. Acs Applied Bio Materials, 6(6): 2158-2171.