
E. Jan Vardaman

TechSearch International Inc.

4801 Spicewood Springs Road

Suite 150

Austin, Texas 78759

Tel: 512-372-8887

Fax: 512-372-8889

www.techsearchinc.com


Semiconductor packaging materials are a key to the success of the semiconductor business in total. Changes in consumer electronics are driving the changes in packaging materials. This presentation highlights the market growth and trends in laminate substrates, lead frames, wafer level packaging dielectrics, bonding wire, encapsulants and molding compounds, thermal interface materials, and solder spheres. The impact of today's BT-resin shortage, laminate substrate shortage, and the rising prices of metals are discussed.