## IP Panel Topic:

### Why is design automation and reuse of analog designs increasingly trailing the digital world?

### Summary:

Demand for high performance in today's systems requires some key IP components to be designed in analog, whereas quick turn around time requires significant use of digital IPs. While there has been significant progress in design automation and design reuse of digital circuits in the last couple of decades, much has not changed for analog design. Design capture in low abstraction level, poor automation of implementation and verification steps, worsening silicon variability etc. combined with several technology nodes/flavors put a lot of pressure on the limited analog design expertise available today.

This panel discussion focuses on these issues and possible solutions. Can some of these design functions be moved from analog domain to digital? What is involved in deploying some of the digital design paradigms and reuse concepts in analog design? What can EDA vendors do to address these issues? What can Fabs do to control process variability to enable reuse of Analog IPs?

### Organizers:

