**Cost Reduction in U.S. Semiconductor Fabrication Environment**


VJ Associates

353964 Killoglin Common

Fremont, California 94536


In the semiconductor fabrication environment, during good times, all cost reduction efforts are directed towards yield enhancement. And in bad times, total plant shutdown and layoffs are not so uncommon to U.S. companies. Very little effort is paid during good times in the U.S. to cutting costs in other high cost centers. Equipment depreciation costs which has a very high priority in a new fab environment is never paid an iota of attention to increase their utilization, especially during a critical operational phase. Adding new equipment prematurely to an existing line can only increase product cost and make the company more vulnerable.

The impact of very low utilization of high cost equipment on overall product cost will be evaluated using the Activity Based Costing (ABC) technique using the PROMIS Shop Floor Control System and RS1 for a newly setup 6" wafer fab.

Results indicate a dramatic decrease in product cost with increased utilization of all capital equipment, especially at the bottlenecks.

This avenue of product cost reduction through increased bottleneck utilization is the second most important cost reduction area that semiconductor manufacturers need to start paying attention to if they are serious about competing in the changing and very volatile IC market.

**211** **1993** **IEEESRM** **A**wared Semiconductor Manufacturing Conference

_Authorized licensed use limited to: University of Durham. Downloaded on April 21,2025 at 19:00:03 UTC from IEEE Xolong. Restrictions apply._