# Digital Signal Multi-Stage Discrete Fourier Transform and Its Practical Applications

Adeliya Burova

Moscow Aviation Institute (National Research University)

Moscow, Russia

frambe@mail.ru

###### Abstract

The issues related to the study of the problem of minimizing hardware costs for software and hardware implementation of algorithms for frequency selection of digital signals on programmable logic devices are considered. The purpose of the study is to define the theoretical foundations of the concept and methodology of the multi-stage discrete Fourier transform without performing multiplication operations. The methods of software and hardware modeling of digital signal processing algorithms were used in the study. The principles of the multi-stage discrete Fourier transform of complex signals are specified only by the operations of adding their time samples. Its methods and digital algorithms are presented. Their basic formulas are given.

_Keywords:_ discrete Fourier transform, finite difference method, multi-speed digital filtering, frequency selection of signals, digital signal processing.

## I Introduction

Frequency selection of digital signals is still the basic tool for their spectral analysis [1-4]. Various methods of digital filtering and discrete Fourier transform (DFT) form the basis of this toolkit [1,5,7]. The computational algorithms of these methods are successfully implemented on digital signal processors and programmable logic devices (PLD) [8-11].

In the software and hardware implementation of such algorithms on the PLD, the use of multi-stage DFT methods of a complex signal based on digital difference filtering, proposed and developed by the author of the report, allows to reduce the hardware costs for frequency selection of digital signals for automatic vibration control of the operating engine of an unmanned car [12]. The digital algorithms of these methods provide deductive processing of a digital signal only by adding its time samples [13-16]. The same algorithms of multi-stage DFT can be used to reduce the hardware costs for digital signal processing (DSP) of automatic control and compensation of the different-tension turbojet engines of the power plant of a twin-engine aircraft in flight [14, 16-18].

## II Purpose and methods

The aim of the study is to define the theoretical foundations of the concept and methodology of multi-stage DFT without performing multiplication operations.

The research uses methods of software and hardware modeling of DSP algorithms [1, 5-6, 19].

## III Theoretical foundations

The theoretical foundations of the idea of multi-stage DFT, proposed and implemented by the author of the report, can and should be considered the following well-known methods:

* the method of multi-speed filtering in relation to the spectral analysis of a digital signal [1-4];
* the finite difference method applied to digital filtering of a discrete signal [6-7, 13-14, 20];
* the Coordinate Rotation Digital Computer (CORDIC) method applied to the DFT of a complex signal [13-14, 16].

## IV Concept

The concept of the proposed adaptive multi-stage DFT method is a gradual ("step by step") \(L\)-step calculation of statistics (estimates) \(\{\mathbf{x}(m_{r}\Omega_{r}\Omega_{r}T_{l})\}\), \(m_{l}\)=0,1,2...\(M_{r}\)-1, \(\Omega\)=\(\sigma_{0D}\)(2\(\cdot\)\(M_{l}\)), \(n\)=0,1,2...\(M_{r}\)-1, \(T_{l}\)=\(\pi\)\(\cdot\)\(M_{l}\)/\(\omega_{0D}\), \(M\)=\(B_{\mathrm{DT}}\)\({}^{l}\), instant spectrum \(\{

[MISSING_PAGE_FAIL:2]

Figure 1: The number _SET_(3\({}^{t}\),2,\(K_{\rm p}\),32) of logical cells for 32-range PLD, which is needed for the 3\({}^{t}\)-points DFT by digital difference filtration with integer difference coefficients for _K_p order of digital difference filtration and the second order of difference

Figure 2: The number _SET_(3\({}^{t}\),3,\(K_{\rm p}\),32) of logical cells for 32-range PLD, which is needed for the 3\({}^{t}\)-points DFT by digital difference filtration with integer difference coefficients for _K_p order of digital difference filtration and the third order of difference

## V Methodology

The methodology of multi-stage DFT is based on the following recurrent methods:

* DFT of a complex signal by multiband digital filtering of its time samples [16];
* multiband digital filtering of a complex signal by a single digital low-pass difference filter [7];
* digital difference filtering with trivial integer difference coefficients of high orders of difference [6];
* synthesis of a digital difference filter with integer difference coefficients of different orders of difference [21];
* energica multi-stage complex DFT of the signal in one digital differential filter [15].

## VI Application areas

Multi-stage DFT methods can and should be used to reduce hardware costs in the software and hardware implementation of digital DFT algorithms on digital signal processors or PLD, in which the equality of the speeds of performing arithmetic operations of multiplication and addition is achieved mainly by hardware [8-11]. The following applications of multi-stage DFT are possible:

* DSP by elementary devices of microelectronics and nanoelectronics [16];
* frequency selection of signals by digital systems of radio engineering and hydroacoustics [13];
* spectral analysis of digital signals by onboard means of passenger airliners and unmanned vehicles [12].

## VII Conclusion

Variability the principles and proposed methods of multi-stage DFT of a complex signal based on its digital difference filtering with integer difference coefficients of different orders of difference provide spectral analysis of this signal only by adding its time samples.

The development of the concept and methodology of such a DFT of a complex signal by the author of the report can and should be considered a further development of the idea of multi-speed digital signal filtering proposed and developed by Professor V. V. Vityazev [1-4], and the idea of digital difference filtering with small-bit difference coefficients proposed and developed by Associate Professor V. S. Kuzkin [6-7, 13-14, 20].

The practical application of digital algorithms of multi-stage DFT without performing algorithmic multiplication operations will reduce the hardware costs for DSP in PLD implementation of methods for automatic vibration control of turbojet and turboprop engines of power plants of medium-and long-haul aircraft in flight.

## References

* Moscow: Radio and Communication, 1993.
- 240 p.
* [2] Vityazev V. V., Zaitsev A. A., & Vityazev S. V. (2008). Multi-speed signal processing: retrospective and current state. Part 1. _Digital Signal Processing_, \(1\),2-21.
* [3] Vityazev V. V., Zaitsev A. A., & Vityazev S. V. (2008). Multi-speed signal processing: retrospective and current state. Part 2. _Digital Signal Processing_, \(3\),2-9.
* Telecom, 2017.
- 336 c.
* [5] Goldenberg, L. M., Matyushkin, B. D., & Polyak, M. N. (1985). _Digital Signal Processing: A Guide_. Moscow: Radio and communications.
* [6] Shinkakov Yu.S., Burov Yu.Ya., Burova A.Yu. (2000). Theory, methods and algorithms of difference digital filtering. Proceedings of the Third International Conference "Digital signal processing and its application" (DSPA'2000), November 29-December 1, 2000., 96-99.
* [7] Burova A. Yu., & Ustenko, T. O. (2020). Digital Algorithms for the Discrete Frequency Selection of Signals that Do Not Use Algorithmic Multiplication Operations. _TEM Journal_, 9(2), 501-506.
* Ryazan: Ryazan State Radio Engineering University, 2007.
- 112 p.
* [9] Stschenko, V. B. (2016). PLD implementation by firm ALTERA: element base, design system and hardware description languages. Moscow: DMK-Press-576 p.
* [10] Burova, A. Yu., Ryapukhin, A. V., & Muntyan, A. R. (2020). Reduced hardware costs with software and hardware implementation of digital methods multistage discrete Fourier transform on programmable logic devices. _Amazonia Investiga_, 9(27), 227-233.
* Moscow: Hot Line
- Telecom, 2021.
- 400 p.
* [12] Burova A.Yu., Kabakov V.V. Automatic control of working car engine vibrations using multi-stage discrete Fourier transformation. Journal of Physics: Conference Series, 2020, 1679(2), 022025.
* [13] Burov Yu.Ya., Burova A.Yu (2010). Deductive processing of digital signals based on the method of finite differences and differential methods of digital filtering and multi-stage discrete Fourier transform, which does not require performing arithmetic operations of multiplication. Russian scientific-technical society of radio engineering, electronics and communication named after A. S. Popov: 65 Scientific session devoted to radio day: Theses of reports. Moscow: Russian Scientific and Technical Society of Radio Engineering, Electronics and Communications, 425-428.
* [14] Burova A.Yu. Digital signal processing without performing arithmetic multiplication operations. Amazonia Investiga. 2020. Vol. 9, No25. pp. 200-205.
* [15] Burova A.Yu., Kabakov V.V. "Unerroric" of multistage discrete Fourier transform of digital signal without arithmetic operations of multiplication. Amazonia Investiga. 2020. Vol. 9, No25, pp. 429-437.
* [16] Burova A.Yu. Reducing the Error of Digital Algorithms for Deductive Signal Processing Based on Their Multi-Stage Discrete Fourier Transform by the Difference Digital Filters. 2020 22th International Conference on Digital Signal Processing and its Applications, DSPA 2020, 9213275.
* [17] Burova A.Yu. Minimisation of asymmetry of thrust of the dual-flow turbojet engines of the airliner in accordance with the results of the system analysis of the thrust parameters. Asia Life Sciences. 2019. 21(2), pp. 629-643.
* [18] Novichkov V.M., Burova A.Yu. Algorithm of Two Turbojets Thrust Asymmetry Minimization for Digital Control System of Twin-Engine Jet Airliner// 2019 International Multi-Conference on Industrial Engineeringand Modern Technologies (Far EastCon), Date Added to IEEE Xplore: 19 December 2019, DOI: 10.1109/Far EastCon.2019.8934285.
* Moscow: Science, 1989
- 496 p.

- N1, pp. 52-54.
* Moscow: Russian Scientific and Technical Society of Radio Engineering, Electronics and Communications, 2000.
- p. 261.