Session 1 Paper 01(Invited)

1000-1020

## 1 Introduction

As a world-leading supplier of extremely reliable high-power diodes, COHERENT is continuously developing and improving not only its laser diode material but also its packaged product portfolio. In this paper we present some of the latest results of our high-power diode laser bar development and present some new product releases incorporating these bars.

## 2 COHERENT Semiconductor Business Unit


As a completely vertically integrated manufacturer, we have control over every critical design and manufacturing step from wafer growth to packaging and integration, and we are able to offer products at every step of the manufacturing process, from unmounted bars to completely integrated systems.

Beside our standard product portfolio, we have a long history in creating and implementing customized solutions. Our strategic emphasis has consistently been and continues to remain focused on quality and reliability, including the continuous improvement of our products and services.

## 3 High-Power Diode Laser Bars

For the main pumping wavelength window between 790 and 830nm, we have optimized our material composition to be capable of higher powers and higher efficiency.. From a conduction-cooled bar with a fill-factor of 30% we can today extract a cw output power of 60W with a reliability of greater than 20,000 hrs. Standard conduction cooled bar packages are also now available with a typical power conversion efficiency (PCE) of up to 59%.

Recently, pumping of Neodymium-doped crystals at a wavelength of 880nm has been gaining in popularity. Pumping at this wavelength reduces thermally induced stresses in the laser crystal, which enables higher output powers with diffraction limited beam quality (TEM00). For this reason we have continued to develop and improve our diode laser bars in this wavelength regime. From a conduction-cooled bar with a fill-factor of 28% we can extract a cw output power of 55W with a PCE of 62%. Typical reliability for our standard products at this wavelength is expected to be greater than 20,000 hours, with lifetests showing almost no degradation in output power through 8,000 hours of operation.

We have also continued to improve the performance of our diode laser bars at 9XXnm. These wavelengths are important for fiber- and disc-laser pumping, as well as for direct diode materials processing. At wavelengths in the 9xx regime, we can extract 80W from a conduction-cooled bar with a fill-factor of 26%, with a PCE of 69%. As with our 808nm and 880nm material systems, typical reliability for our 9XXnm products is \(>\)20,000 hours.

978-1-4244-5547-8/09/$26.00 (c)2009 IEEEIncreasingly customers are asking for diodes that can be run at high operation temperatures. In order to serve this request we have developed our material systems to be capable of running at high operation temperatures, in particular by maintaining high PCEs even at temperatures as high as 70C. Figure 1 shows the dependence of diode laser power and PCE on operation temperature for 790-830nm material (left) and 9XXnm material (right).

## High Performance Packaging Improvements

In addition to improving our material systems, we have made advances in our packaged bar products. In the first section of this talk, we presented improvements in our bar technology as mounted on conduction-cooled bar packages (CCPs). In addition to supporting higher powers, our CCPs have also been optimized to produce reduced smile and improved smile stability.

Vertical conduction cooled QCW stacks (also known as G-stacks) are now available at standard power levels of up to 200W QCW per bar. As an example, we demonstrate an 808nm 7-bar stack with an output power of 1.75kW in QCW operation mode (1% duty cycle, 250us pulsewidth) and a wallplug efficiency of 59%. Our G-stacks are designed to leverage the high-temperature capability of our AAA\({}^{\text{TM}}\) material system, and can be operated at temperatures of 70 deg C.

Micro-channel cooled packages and vertical stacks are available at powers of 100W CW per bar at wavelengths of 808 and 9XXnm. Like our conduction cooled bar packages, these are available with a low-smile option for easy fiber-coupling with micro-optics.

Beside vertical arrays, horizontal arrays are also of interest to the diode pumping community, in particular for transverse pumping of solid-state lasers. With a 5-bar horizontal array we can achieve an output power of 1.25kW in QCW operation mode at 808nm with a duty-cycle of 10% and a pulse width of 250\(\upmu\)sec. With Coherent's PulseLife\({}^{\text{TM}}\) water-cooled arrays, CW output powers of up to 50W per bar are possible. Because the diode laser bars are electrically isolated from the water channel, the use of DI water is not required.

## Conclusion

In this paper we have presented recent results of our high-power diode laser bar development. The results are transferred directly into new products which are available for our customers now. Improvements were achieved in output power, efficiency and stability of performance under operation with high temperature.

## Email Addresses


Figure 1: Dependence of output power and PCE on operation temperature