


2450 Scott Blvd, Suite 312


## I Introduction

The continued need for increasing productivity of semiconductor equipment has necessitated looking for materials which can provide enhanced performance with less maintenance. In spite of the very stringent demands to address the new semiconductor technology nodes, new materials have been and are being developed to increase the operating life of semiconductor manufacturing equipment components. These materials range from new elastomeric seals, ceramics, high purity quartz, silicon carbides and sapphire to composites of other metal carbides and oxides including high temperature plastics.

A review is given of the materials most commonly used today and the limitations these impose in increasing production time and process performance. The etching of materials in etch equipment necessitates replacing parts on a frequent basis. By providing such materials coated with etch resistant films, the part lifetime is increased, however the part's effect on system performance has to be well understood to substitute a coated part. In addition, the performance of the coating on the part has to be addressed to assure that suitable adhesion and very low particulation will result. Several examples are described and how they were formulated will be discussed.

## II Elastomeric Seal Materials

The need for long lasting seals used between parts requires that seals have very low outgassing and also permeability to the gases being used for processing. The development of seal materials has followed the illustration shown in Fig. 1, where common used fluoroelastomers [1] derived from Nitrile Rubber (NBR) is modified with attachment of fluorine atoms in the place of the smaller hydrogen atoms forming fluoroelastomers (FKM). The fluorine atoms act as buffers of the carbon backbone within the elastomer material resulting in a more chemically resistant seal. This also helps in increasing the temperature resilience of the materials as depicted in Fig. 2 where the bonding energy of the carbon and hydrogen versus fluorine is shown [2, 3]. It is seen that the disassociation energy for the latter requires nearly two times the energy, thus making the material more temperature resistance.

To further enhance the seals' properties for chemical and temperature resilience, additional hydrogens are replaced by fluorine resulting in the perfluoroelastomer (FFKM) material, having a capability to operate at up to 300, in harsh chemical environments of fluorine radicals used for etching films on wafers, however; the worst are the CVD systems which utilize NF3 derived cleaning gases for

Fig. 1: Evolution of elastomeric materials for semiconductor applications.

Fig. 2: Bonding energies of common bonds found in elastomer polymers

[MISSING_PAGE_FAIL:2]

New material evolution with quartz has also improved its properties to address more stringent requirements. Utilizing high purity quartz, the quartz surface was textured resulting in improved adhesion of films that may be deposited on the quartz surface. Texturizing the surface has the effect of reducing the differences between the expansion coefficients of the deposited film and the base quartz material. For CVD applications, it becomes more difficult for microcracks to form in the deposited film thus extending the life of the quartz part [10]. The surface roughness of the quartz was increased about 10%, thereby the surface defects are reduced which reduces the particulate contamination from the quartz surface.

Silicon carbide (SiC) has become the material [11] of choice for making furnace ware more mechanically ruggedness as needed to increase the time between replacements. With silicon carbide having a better resistance to cleaning gases such as \(\mathrm{NF_{3}}\), results of a comparisons of different materials is shown in Fig. 7. A number of ways are available for forming silicon carbide, from standard "ceramic" manufactured by sintering together SiC powder, to a conversion processing from a graphite base. The sintered materials are then machined to the final dimension parts. With the conversion process, a molded part is made of graphite that is nearly the desired dimensions, referred to net-shaped, and then some final machining is performed to yield the desired part.

Recent capabilities in making sapphire have resulted in it being used for various parts within the equipment. Most applications involve the use of its excellent resistance to the cleaning gases of \(\mathrm{NF_{3}}\) and where used, \(\mathrm{SF_{6}}\). Its excellent optical transparency over a wide spectral bandwidth also permits usage where spectroscopy is used for end-point detection. Sapphire parts are made from a boule of grown sapphire, this material used primarily for very high quality optical windows or optical components. Other methods for making sapphire are used for large windows and plates, for example making gas dispersion heads, referred to as shower heads. For some applications, the sapphire can be made into light pipes for transmitting of images. Examples of complex parts are shown in Fig. 8 to indicate how sapphire can be used in many applications.

New materials based on plastics have been formulated and can be used in semiconductor manufacturing equipment. In the deposition of films, the films also deposit on the process chamber walls requiring aggressive gases to clean them off before they begin particulate. Also, the gaseous cleaning requires excessive time, all lost for production with manual cleaning intervention required at times. New high performance plastics have been developed allowing the fabrication and placement of a shield inside the chamber. The shield is then removed after a suitable time of deposition and replaced, allowing the equipment to be more quickly placed back into production.

Additionally, plastics with inorganic coatings are being used as a means to use suitable lower cost materials for components within semiconductor equipment. In the

Figure 8: Complex parts made of sapphire.

Figure 6: Improvement of \(\mathrm{Al_{2}O_{3}}\) ceramic with surface treatments.

Figure 7: Comparison of various materials’ etch rate in \(\mathrm{NF_{3}}\) plasma.

cleaning of wafers in aqueous baths, the plastics used are chemically resistant; however it is desired to make the surfaces hydrophobic to minimize the wetting of the surfaces other than those of the wafer in process. With new films of refined PTFE or diamond like coatings (DLC), such hydrophobicity is attainable. An example of such characteristics is given in Figure 9, where the hydrophobicity is given (in terms of a contact angle) for several film types.

The use of films for improving the longevity of semiconductor equipment parts lends itself to making the parts of lower cost materials and having a coating become the interface to the process environments. Such is the case with the domes used as the cover of the process chamber in etch equipment; the domes being made of alumina, which are then coated with yttria (Y\({}_{2}\)O\({}_{3}\)) to enhance etch resistance. Similar techniques are being employed with DLC coatings and hard diamond coatings. An interesting application for the diamond is on bearings utilized in high performance vacuum pumps.

## IV Summary

It is then noted that substantial gains in productivity can be achieved with new materials that have or are being developed. New manufacturing technology combined with new material formulations are ongoing leading to enhanced manufacturing productivity. It should be noted that collaboration with other industries has been a major factor in finding materials suitable for semiconductor equipment, with some adaptation required for stringent cleanliness and very low impurity levels.

