
Session XV

Medical and




The small physical size and specialized electrical characteristics of custom integrated circuits make them ideal for the development of new complex medical electronic systems.

A broad range of fabrication technologies, ranging from CMOS to bipolar and thin film hybrid techniques, have been applied in three papers to be presented.

Uniqueness in the circuit design approaches, particularly for the part of the system implanted into the patient, is essential to satisfy the requirements of micropower operation, low-noise and a wide variety of electrical functions ranging from high density digital to precision analog circuits. The almost constant temperature environment of an implanted circuit can lead to reduced circuit complexity. Integrated circuits for ultrasonic systems will be discussed in two talks, one for an advanced form of imaging of body organs and another for the measurement of blood flow.

The increasing penetration of integrated circuits into TV sets will be explored in another report. In addition to analog ICs found in most modern TV sets, digital functions have, in some cases, replaced discrete or integrated analog functions. A vertical synchronizing circuit, to be described, provides an example of the application of digital techniques, becoming economically practical by the use of injection logic.

Electronic ignition systems in automobiles have become standard in many models, yet circuit approaches for the various ignition systems differ significantly. A Q-modulated oscillator, the heart of an ignition control IC, will be described in a concluding paper.