**SCW4** **Tunable Line-Narrowed Semiconductor Laser**

**for Laser Radar Applications**

W. R. Babbitt, R. L Hagman, and J. A. McGarvey


High performance distance and velocity measurement systems are required to meet the demands of various aerospace systems. These systems include aircraft guidance and control, threat/hazard detection and avoidance, and control of large space structures. High performance measurement systems also are required in the manufacturing, control, and health monitoring of system components. In this paper, the development of a tunable, line-narrowed semiconductor laser for use in high precision range measurement systems will be discussed.

The technique of resonant optical feedback[1] (ROFB) is used to narrow the linewidth of the laser, as well as to lock the laser to one of the modes of the external resonant cavity. A detailed discussion of the theory and operation of an ROFB system is given in reference 2. A schematic of the basic ROFB system is shown in figure 1. Light incident on the external cavity is retroreflected when it is on resonance with one of the cavity modes. When this light is injected at an appropriate level back into the semiconductor laser cavity, it greatly increases the gain at the cavity mode frequency, thus pulling the frequency of the laser within \(\Delta\nu_{c}\)/2 of the cavity mode frequency, where \(\Delta\nu_{c}\) is the linewidth of the external cavity. At the same time, the long storage time of the external resonant cavity causes the linewidth of the semiconductor laser to be narrowed significantly.

The operating linewidth of the ROFB laser system is significantly influenced by \(\Delta\nu_{c}\), the level of the feedback, and the noise spectrum of the free-running laser. In practice, linewidth reduction can range from two to over five orders of magnitude.[3] The actual laser's operating frequency and stability depend on several of the system parameters, including the free-running semiconductor laser frequency, the cavity mode frequency, and the distance between the laser and external cavity. These parameters can be used to tune the operating frequency of the laser while maintaining a narrow linewidth. In practice, the influence of the free-running laser frequency is reduced by two to three orders of magnitude; the frequency of the cavity mode being the dominant determinant of the operating frequency.

Figure 2 shows the design of a tapped fiber ring resonator which can replace the confocal Fabry-Perot cavity in figure 1. A fiber optic system has the advantages of compactness, robustness, ease of alignment, and tuning rate over bulk optic systems. An ROFB system with the above tapped fiber ring resonator is currently being assembled and tested. The resonator has a free spectral range of 1.28 GHZ and a measured finesse of 65. The laser is a commercial GaAlAs semiconductor laser with an output power of roughly 12 mW. The linewidth of the ROFB system is predicted to be roughly 10 kHz and the expected tuning range/rate is 8 GHz in 100 \(\upmu\)sec. Analysis of such a system for high precision, free space ranging[4] indicates that range resolutions on the order of 100 microns should be obtainable at a range of 100 meters. Recent results will be presented.

[MISSING_PAGE_FAIL:2]